apiVersion: v1
kind: Pod
metadata:
  name: newpod
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
          protocol: "TCP"
      envFrom:
        - configMapRef:
            name: daws

                  